"""add_reopen_count_to_tickets

Revision ID: 2eff2e137a7e
Revises: a8b1c2d3e4f5
Create Date: 2026-05-08 22:51:40.078456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eff2e137a7e'
down_revision: Union[str, Sequence[str], None] = 'a8b1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_jobs_status_run_after_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_knowledge_articles_search_filters'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_search_vector'), table_name='knowledge_articles', postgresql_using='gin')
    op.drop_column('knowledge_articles', 'search_vector')
    op.drop_index(op.f('ix_knowledge_embedding_jobs_status_run_after_id'), table_name='knowledge_embedding_jobs')
    op.alter_column('ticket_comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket_comments', 'author_username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ticket_comments', 'author_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_ticket_comments_author_id'), table_name='ticket_comments')
    op.drop_index(op.f('ix_ticket_comments_created_at'), table_name='ticket_comments')
    op.create_foreign_key(None, 'ticket_comments', 'users', ['author_id'], ['id'])
    op.add_column('tickets', sa.Column('reopen_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reopen_count')
    op.drop_constraint(None, 'ticket_comments', type_='foreignkey')
    op.create_index(op.f('ix_ticket_comments_created_at'), 'ticket_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_comments_author_id'), 'ticket_comments', ['author_id'], unique=False)
    op.alter_column('ticket_comments', 'author_role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ticket_comments', 'author_username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ticket_comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_knowledge_embedding_jobs_status_run_after_id'), 'knowledge_embedding_jobs', ['status', 'run_after', 'id'], unique=False)
    op.add_column('knowledge_articles', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('((((setweight(to_tsvector(\'russian\'::regconfig, (((((COALESCE(title, \'\'::character varying))::text || \' \'::text) || COALESCE(keywords, \'\'::text)) || \' \'::text) || (COALESCE(request_type, \'\'::character varying))::text)), \'A\'::"char") || setweight(to_tsvector(\'simple\'::regconfig, (((((COALESCE(title, \'\'::character varying))::text || \' \'::text) || COALESCE(keywords, \'\'::text)) || \' \'::text) || (COALESCE(request_type, \'\'::character varying))::text)), \'A\'::"char")) || setweight(to_tsvector(\'russian\'::regconfig, COALESCE(problem, \'\'::text)), \'B\'::"char")) || setweight(to_tsvector(\'russian\'::regconfig, ((COALESCE(body, \'\'::text) || \' \'::text) || COALESCE(when_to_escalate, \'\'::text))), \'C\'::"char")) || setweight(to_tsvector(\'simple\'::regconfig, COALESCE(search_text, \'\'::text)), \'D\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_knowledge_articles_search_vector'), 'knowledge_articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_knowledge_articles_search_filters'), 'knowledge_articles', ['is_active', 'access_scope', 'department', 'request_type'], unique=False)
    op.create_index(op.f('ix_ai_jobs_status_run_after_id'), 'ai_jobs', ['status', 'run_after', 'id'], unique=False)
    # ### end Alembic commands ###
